### ISSUE TITLE
Helvetica in math font

### ISSUE THREAD

**Issue by pucicu** [emtpb/proposal_dfg#1]
I suggest to add `\usepackage[helvet]{sfmath}` in order to have Helvetica font also in the budget's numbers.

**Comment by lndr** [comment]
While it would be nice to have the budget numbers in a sans serif font (to be fair: no one noticed so far), your proposal would also change all equations to be sans serif, which I'd say most people would not find desirable. Any idea how to change it for the budget numbers only?

**Comment by lschmalen** [comment]
Works by adding "detect-all" to the \sisetup in proposal.sty. The drawback is that all occurrences of \num will be cast in sans serif font. For me not really an issue as not using \num in equations. I created a pull request, but somebody should check if this is really not causing trouble at some other place

**Comment by lndr** [comment]
Fixed in #3 
Again, I'd like to ask you if you have been successful using this template. If so, we could add your projects to the list in the readme.
